/* Catalogue of every CICOD-AI component. The hub page (index.html) is generated from this list.
   code = ID in AI_Augmentation_Opportunities.md · phase = rollout phase (1 = 0–90 days). */
window.AI_REGISTRY = [
  // ───────────── ECMS ─────────────
  { group: 'ecms', slug: 'smart-routing', code: 'E-T1', phase: 1, title: 'Smart Intake & Routing', screen: 'Tasks → Create Task', tag: '<ai-smart-routing>', summary: 'Suggests queue, queue type, priority and assignee for every new request, with reasons and a duplicate warning.' },
  { group: 'ecms', slug: 'task-brief', code: 'E-T2 · E-T4', phase: 1, title: 'Task Brief & Suggested Reply', screen: 'Tasks → Task detail', tag: '<ai-task-brief>', summary: 'A five-line summary of the task timeline, the next best action, and a drafted remark or reply.' },
  { group: 'ecms', slug: 'sla-predictor', code: 'E-T3', phase: 1, title: 'SLA Risk & Smart Escalation', screen: 'Tasks → All Tasks', tag: '<ai-sla-risk>', summary: 'Predicts which tasks will breach their SLA and proposes an early escalation, with the reason.' },
  { group: 'ecms', slug: 'approval-copilot', code: 'E-T7', phase: 2, title: 'Approval Copilot', screen: 'Tasks → Task Approvals', tag: '<ai-approval-copilot>', summary: 'A pre-digested approval pack with a policy check, risk flags and a recommended decision. Supports safe bulk approval.' },
  { group: 'ecms', slug: 'email-to-task', code: 'E-S1', phase: 1, title: 'CICOD-AI Email-to-Task', screen: 'Settings → Email Integration', tag: '<ai-email-triage>', summary: 'Classifies incoming mail, extracts the request and attachments, matches the contact and routes it as a task.' },
  { group: 'ecms', slug: 'memo-copilot', code: 'E-M1 · E-M2', phase: 1, title: 'Memo Copilot', screen: 'Memos → Create Memo', tag: '<ai-memo-copilot>', summary: 'Drafts a formal official executive memo from bullet points. Rewrites, shortens and adjusts tone inside the editor.' },
  { group: 'ecms', slug: 'memo-minutes', code: 'E-M3 · E-M4', phase: 1, title: 'Minute Summary & Action Items', screen: 'Memos → Memo view / Draft Reviews', tag: '<ai-minute-summary>', summary: 'Summarises long minute chains and turns "please treat" instructions into tracked ECMS tasks.' },
  { group: 'ecms', slug: 'prompt-to-workflow', code: 'E-W1', phase: 2, title: 'Prompt-to-Workflow', screen: 'Workflows → Create Workflow', tag: '<ai-workflow-builder>', summary: 'Describe a process in plain English and get an editable draft: queue, statuses, form, escalation and approvals.' },
  { group: 'ecms', slug: 'prompt-to-form', code: 'E-W2', phase: 2, title: 'CICOD-AI Form Builder', screen: 'Forms → Create Form', tag: '<ai-form-builder>', summary: 'Generates form fields from a description, or from a photo or PDF of an existing paper form.' },
  { group: 'ecms', slug: 'setup-wizard-mapper', code: 'E-W5', phase: 2, title: 'Setup Wizard CICOD-AI Mapper', screen: 'Settings → Setup Wizard', tag: '<ai-org-mapper>', summary: 'Maps any nominal roll or org chart to departments, roles, users and line managers, and deduplicates roles.' },
  { group: 'ecms', slug: 'dashboard-insights', code: 'E-D1 · E-D2 · E-D4', phase: 1, title: 'Dashboard Insights', screen: 'Dashboard → Workflow Dashboard', tag: '<ai-dashboard-insights>', summary: '"Explain this dashboard" narratives, anomaly alerts and data-consistency checks.' },
  { group: 'ecms', slug: 'nl-reports', code: 'E-D5', phase: 1, title: 'Ask for a Report', screen: 'Reports', tag: '<ai-report-builder>', summary: 'Type the report you need in plain English and get a chart, a table and an export.' },
  { group: 'ecms', slug: 'contact-dedup', code: 'E-C1 – E-C4', phase: 1, title: 'Contact Dedup & 360 Summary', screen: 'Contacts', tag: '<ai-contact-insights>', summary: 'Finds and merges duplicate contacts, cleans junk records and summarises each contact\'s history.' },
  { group: 'ecms', slug: 'audit-copilot', code: 'E-A1 · E-A2', phase: 1, title: 'Audit Copilot', screen: 'Reports → Audit Log', tag: '<ai-audit-copilot>', summary: 'Answers questions about the audit log in plain English and flags anomalies such as repeat approvals and off-hours activity.' },
  { group: 'ecms', slug: 'smart-dispatch', code: 'E-U3 · E-U4', phase: 2, title: 'Smart Dispatch & Workload Balancing', screen: 'Resources → All Resources', tag: '<ai-smart-dispatch>', summary: 'Rebalances open work across resources by skill, shift, schedule and load, and flags invalid shifts.' },

  // ───────────── CICOD (other apps) ─────────────
  { group: 'cicod', app: 'Workspace', slug: 'daily-brief', code: 'H1 · H3', phase: 1, title: 'CICOD-AI Daily Brief', screen: 'Workspace → Home', tag: '<ai-daily-brief>', summary: 'Turns the "Needs you today" counters into a ranked briefing with SLA risks and meeting prep.' },
  { group: 'cicod', app: 'Workspace', slug: 'ask-cicod', code: 'H2 · H5', phase: 2, title: 'Ask CICOD (search & commands)', screen: 'Global header, all apps', tag: '<ai-ask-cicod>', summary: 'Plain-English search and actions across Drive, ECMS, InMail and IMS, trimmed to what the user may see, with citations.' },
  { group: 'cicod', app: 'Workspace', slug: 'request-finder', code: 'R1 · R2 · R3', phase: 1, title: 'Request Finder & Document Autofill', screen: 'Workspace → Request / webforms', tag: '<ai-request-finder>', summary: '"Describe your need" opens the right form pre-filled. Uploading an ID or letter fills in the fields.' },
  { group: 'inmail', app: 'InMail', slug: 'inmail-compose', code: 'M1 · M2 · M5', phase: 1, title: 'InMail Smart Compose & Summaries', screen: 'InMail → Compose / Inbox / Circular', tag: '<ai-mail-assist>', summary: 'Drafts official letters and circulars, summarises threads and suggests the audience.' },
  { group: 'drive', app: 'Drive', slug: 'drive-doc-assistant', code: 'D1 · D2 · D13', phase: 1, title: 'Document Assistant', screen: 'Drive → File viewer', tag: '<ai-doc-assistant>', summary: 'Summarise a document or chat with it, with citations, while respecting its classification.' },
  { group: 'drive', app: 'Drive', slug: 'drive-smart-upload', code: 'D4 · D5', phase: 2, title: 'Smart Upload: Classification & Filing', screen: 'Drive → NEW → Upload', tag: '<ai-smart-upload>', summary: 'Suggests the classification level, detects personal data and proposes a folder and tags when a file is uploaded.' },
  { group: 'drive', app: 'Drive', slug: 'drive-historic-ocr', code: 'D3 · D6', phase: 1, title: 'Historic Files OCR & Search', screen: 'Drive → Historic Files', tag: '<ai-ocr-search>', summary: 'Makes scanned file jackets searchable and extracts their dates, references and parties.' },
  { group: 'drive', app: 'Drive', slug: 'drive-smart-signature', code: 'D7 · D8', phase: 2, title: 'Smart Signature & Routing', screen: 'Drive → Sign File', tag: '<ai-smart-signature>', summary: 'Automatically identifies signatories, places signature fields, and generates a pre-signing obligation brief for the signers.' },
  { group: 'cicod', app: 'Conference', slug: 'meeting-minutes', code: 'C2 · C3 · C5', phase: 2, title: 'CICOD-AI Minutes of Meeting', screen: 'Conference → Recordings', tag: '<ai-meeting-minutes>', summary: 'Produces a transcript, minutes, decisions and action items. Saves the minutes to Drive and creates ECMS tasks.' },
  { group: 'assets', app: 'Assets', slug: 'ims-invoice-capture', code: 'A2 · A7', phase: 2, title: 'Invoice Capture & 3-Way Match', screen: 'Assets → Receive Asset / Payables', tag: '<ai-invoice-capture>', summary: 'Reads the invoice or waybill, pre-fills the receipt, matches it against the request and flags price outliers.' },
  { group: 'assets', app: 'Assets', slug: 'ims-stock-variance', code: 'A3', phase: 2, title: 'Stock-Take Variance Explainer', screen: 'Assets → Stock Taking Mang.', tag: '<ai-variance-explainer>', summary: 'Explains each variance from movement history and flags suspicious patterns before approval.' },
  { group: 'assets', app: 'Assets', slug: 'ims-registry-guardian', code: 'A1 · A4 · A6', phase: 1, title: 'Registry Guardian & Forecast', screen: 'Assets → Asset Registry', tag: '<ai-registry-guardian>', summary: 'Flags impossible KPI values and duplicate master data, and forecasts reorder points.' },
  { group: 'cicod', app: 'Portal', slug: 'citizen-assistant', code: 'S1 · S2 · S3', phase: 2, title: 'Citizen Assistant', screen: 'Paperless Service Portal', tag: '<ai-citizen-assistant>', summary: 'Conversational intake that picks the right queue, fills the form and explains request status in plain language.' },
  { group: 'cicod', app: 'PMS', slug: 'pms-appraisal-copilot', code: 'P1 · P2', phase: 3, title: 'Appraisal Copilot', screen: 'PMS → Appraisals (assumed)', tag: '<ai-appraisal-copilot>', summary: 'Writes SMART KPIs and drafts appraisals from evidence across ECMS and Drive.' },
];
